### ISSUE TITLE
Change VirtioMediaHostMemoryMapper trait add_mapping return type

### ISSUE THREAD

**Issue by aesteve-rh** [chromeos/virtio-media#7]
Currently, `add_mapping` at https://github.com/chromeos/virtio-media/blob/main/device/src/lib.rs#L172
expects the guest physical address to be returned. Apparently, it assumes that backend and frontend are the same process, which may not always be the case. And this is not compliant with vhost-user semantics.

The guest should be aware already of the shared memory's base address. Therefore, returning an offset would suffice, and since the offset should correlate with the offset requested in the parameters, probably the return could just be empty: `Result<(), i32>`.

**Comment by Gnurou** [comment]
Should be fixed by c6b51d558b76fab454983c237e5bfa0dd6e756b0 (forgot to mention this issue in the commit message). Please reopen if there are remaining issues!

**Comment by Gnurou** [comment]
For the record, we are still returning because we don't have a guarantee that the SHM region will cover the full 4GB MMAP address space. It's safer to have the option to remap, and hosts who want to do 1:1 mapping can do so trivially.
